### ISSUE TITLE
connect a USB-MIDI keyboard via a USB hub 

### ISSUE THREAD

**Issue by copych** [serifpersia/pianoled-esp32#3]
Hello @serifpersia nice work! I have a midi keyboard with a micro-usb female connector, so I usually use a USB hub to connect it to modern USB-C hosts. Is there a way to use such hub with ESP32s2 or s3 in this project, or this USB-host implementation only serves the first connected device? Is there a chance to somehow advance in this matter?

**Comment by serifpersia** [comment]
Hi there!

I don't think ESP32 can use the MIDI USB device connected via USB HUB. It all depends how the Hub works. 
ESP32 USB OTG interface can work with any usb 1.1 speed compliant device as long as you have a driver for it example driver for usb keyboard, mouse, printer, midi etc. But its highly likely it won't be able to be used with USB HUB. 

You do realize you can use standard USB OTG C or micro-b adapter depending on what usb port the esp32 s2 s3 boards have. The OTG cable has female USB A so you can connect your midi device to that otg adapter which is required in any case since most usb midi devices have a cable with usb A male connection. If you have any other questions feel free to ask here or in my discord server you can find it in the github page. If you don't have anything else related to issues with the project itself I will close this as resolved shortly after
